{% set name = "tetraframework" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tetraframework-{{ version }}.tar.gz
  sha256: c28fed6bd752685cf1611cc8edde321951c9e13458390861e8a489c07d567263

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - tetra >=0.1.0

test:
  imports:
    - tetra
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/tetraframework/
  summary: Full stack component framework for Django using Alpine.js
  license_file: LICENSE
  license: MIT

extra:
  recipe-maintainers:
    - thewchan
