{% set name = "tetraframework" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tetraframework-{{ version }}.tar.gz
  sha256: c28fed6bd752685cf1611cc8edde321951c9e13458390861e8a489c07d567263

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - cryptography >=37.0.1
    - django
    - pip
    - python >=3.7
    - python-dateutil >=2.8.2
  run:
    - cryptography >=37.0.1
    - django >=3.2.0
    - python >=3.7
    - python-dateutil >=2.8.2
    - sourcetypes >=0.0.4

test:
  imports:
    - tetra
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.tetraframework.com
  dev_url: https://github.com/samwillis/tetra
  doc_url: https://www.tetraframework.com/docs/
  summary: Full stack component framework for Django using Alpine.js
  license_file: LICENSE
  license: MIT

extra:
  recipe-maintainers:
    - thewchan
